### ISSUE TITLE
ansible-playbook -b --private-key \      ../keys/tf-kube kubespray-2.18.1/cluster.yml - Failed "msg": "Ansible must be between 2.9.0 and 2.12.0"

### ISSUE THREAD

**Issue by surfd4wg** [alicek106/aws-terraform-kubernetes#4]
root@terraform-aws-kube:/# ansible --version
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
  jinja version = 2.11.3
  libyaml = True

![2022-04-18_11-20-23](https://user-images.githubusercontent.com/63609504/163847793-39432ec9-ad2b-407c-a0d1-d67d1f856f18.png)

**Comment by surfd4wg** [comment]
Solution:
Do a version on your ansible.
```
ansible version
```
Then edit the kubespray-x.xx.x/ansible_version.yml file to.
```
  vars:
    minimal_ansible_version: 2.9.0
    minimal_ansible_version_2_10: 2.10.11
    maximal_ansible_version: 2.16.0
    ansible_connection: local
```
Make sure the maximal_ansible_version is greater than your running version.
